apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-php.fullname" . }}
  labels:
    {{- include "sample-php.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.create }}
automountServiceAccountToken: true
{{- end }}
