apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-nodejs.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000 # Update this based on the app's exposed port
  selector:
    app: {{ .Chart.Name }}
