apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-nodejs.fullname" . }}
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.create | default true }}
automountServiceAccountToken: true
{{- end }}
