name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore .NET dependencies
      working-directory: ./dotnet-hello-world
      run: |
        dotnet restore

    - name: Build .NET application
      working-directory: ./dotnet-hello-world
      run: |
        dotnet build --configuration Release

    - name: Run tests for .NET app
      working-directory: ./dotnet-hello-world
      run: |
        dotnet test --configuration Release

    - name: Build Docker image for .NET
      working-directory: ./dotnet-hello-world
      run: |
        docker build -t sample-dotnet:latest .

    - name: Tag Docker image to ACR (Dotnet)
      working-directory: ./dotnet-hello-world
      run: |
        docker tag sample-dotnet:latest ${{ secrets.ACR_NAME }}.azurecr.io/sample-dotnet:latest

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image for .NET to ACR
      run: |
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/sample-dotnet:latest

  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy .NET app to Azure App Service
      run: |
        az webapp create --name hello-world-api --resource-group RGroup --plan MyAppServicePlan --runtime 'DOTNET|8.0' --deployment-container-image-name ${{ secrets.ACR_NAME }}.azurecr.io/sample-dotnet:latest
